[tool.poetry]
name = "house-explorer-backend"
version = "0.1.0"
description = "Flask app for backend of house-explorer app"
authors = ["Sasha Kirillov <sasha.anaximander@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
beautifulsoup4 = "==4.9.1"
flask = "==1.1.2"
flask-bcrypt = "==0.7.1"
flask-cors = "==3.0.8"
flask-sqlalchemy = "==2.4.3"
gunicorn = "==20.0.4"
psycopg2 = "==2.8.5"
pyjwt = "==1.7.1"
python-dotenv = "==0.13.0"
requests = "==2.24.0"
sqlalchemy = "==1.3.17"
sqlalchemy-utils = "==0.36.6"
transliterate = "==1.10.2"

[tool.poetry.dev-dependencies]
black = "==19.10b0"
flake8 = "==3.8.3"
pytest = "==5.4.3"
termcolor = "==1.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
